#pragma once

#include "impl/dispatch.hpp"
#include "impl/func_attr.hpp"

#if !defined(KSIMD_DISPATCH_THIS_FILE)
    #error "has not defined KSIMD_DISPATCH_THIS_FILE"
#endif

#define KSIMD_DETAIL_CHECK_DISPATCH_FILE_INCLUDED

#undef KSIMD_ONCE
#define KSIMD_ONCE 0

// AVX2 + FMA3 + F16C
#if defined(KSIMD_INSTRUCTION_FEATURE_AVX2_MAX)
    // KSIMD_DYN_INSTRUCTION
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_AVX2_MAX

    // KSIMD_DYN_FUNC_ATTR
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_INTRINSIC_ATTR_AVX2_MAX

    // KSIMD_DYN_DISPATCH_LEVEL
    #undef KSIMD_DYN_DISPATCH_LEVEL
    #define KSIMD_DYN_DISPATCH_LEVEL KSIMD_DYN_DISPATCH_LEVEL_AVX2_MAX

    // dispatch if not fallback
    #if (KSIMD_INSTRUCTION_FEATURE_AVX2_MAX != KSIMD_INSTRUCTION_FEATURE_FALLBACK_VALUE)
        #include KSIMD_DISPATCH_THIS_FILE
    #endif
#endif

// Scalar
#if defined(KSIMD_INSTRUCTION_FEATURE_SCALAR)
    // KSIMD_DYN_INSTRUCTION
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_SCALAR

    // KSIMD_DYN_FUNC_ATTR
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_INTRINSIC_ATTR_SCALAR

    // KSIMD_DYN_DISPATCH_LEVEL
    #undef KSIMD_DYN_DISPATCH_LEVEL
    #define KSIMD_DYN_DISPATCH_LEVEL KSIMD_DYN_DISPATCH_LEVEL_SCALAR

    // dispatch if not fallback
    #if (KSIMD_INSTRUCTION_FEATURE_SCALAR != KSIMD_INSTRUCTION_FEATURE_FALLBACK_VALUE)
        #include KSIMD_DISPATCH_THIS_FILE
    #endif
#endif


// last dispatch
// once
#undef KSIMD_ONCE
#define KSIMD_ONCE 1

#undef KSIMD_DISPATCH_THIS_FILE
