#pragma once

#include "impl/dispatch.hpp"

#if !defined(KSIMD_DISPATCH_THIS_FILE)
    #error "has not defined KSIMD_DISPATCH_THIS_FILE"
#endif


#undef KSIMD_ONCE
#define KSIMD_ONCE 0

// AVX2 + FMA3 + F16C
#if defined(KSIMD_INSTRUCTION_FEATURE_AVX2) && defined(KSIMD_INSTRUCTION_FEATURE_FMA3) && defined(KSIMD_INSTRUCTION_FEATURE_F16C)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_AVX2_FMA3_F16C

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 AVX2_FMA3_F16C
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_AVX2_FMA3_F16C_INTRINSIC_ATTR

    #include KSIMD_DISPATCH_THIS_FILE
#endif

// AVX2
#if defined(KSIMD_INSTRUCTION_FEATURE_AVX2)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_AVX2

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 AVX2
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_AVX2_INTRINSIC_ATTR

    #include KSIMD_DISPATCH_THIS_FILE
#endif

// AVX
#if defined(KSIMD_INSTRUCTION_FEATURE_AVX)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_AVX

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 AVX
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_AVX_INTRINSIC_ATTR

    #include KSIMD_DISPATCH_THIS_FILE
#endif

// SSE4.1
#if defined(KSIMD_INSTRUCTION_FEATURE_SSE4_1)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_SSE4_1

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 SSE4_1
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_SSE4_1_INTRINSIC_ATTR

    #include KSIMD_DISPATCH_THIS_FILE
#endif

// SSE3
#if defined(KSIMD_INSTRUCTION_FEATURE_SSE3)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_SSE3

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 SSE3
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_SSE3_INTRINSIC_ATTR

    #include KSIMD_DISPATCH_THIS_FILE
#endif

// SSE2 (may be fallback)
#if defined(KSIMD_INSTRUCTION_FEATURE_SSE2)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_SSE2

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 SSE2
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_SSE2_INTRINSIC_ATTR

    #if (KSIMD_INSTRUCTION_FEATURE_SSE2 != KSIMD_INSTRUCTION_FEATURE_FALLBACK_VALUE)
        #include KSIMD_DISPATCH_THIS_FILE // dispatch if not fallback
    #endif
#endif

// SSE
#if defined(KSIMD_INSTRUCTION_FEATURE_SSE)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_SSE

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 SSE
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_SSE_INTRINSIC_ATTR

    #include KSIMD_DISPATCH_THIS_FILE
#endif

// Scalar (may be fallback)
#if defined(KSIMD_INSTRUCTION_FEATURE_SCALAR)
    #undef KSIMD_DYN_INSTRUCTION
    #define KSIMD_DYN_INSTRUCTION KSIMD_DYN_INSTRUCTION_SCALAR

    // 此时 KSIMD_DYN_FUNC_ATTR 等于 Scalar
    #undef KSIMD_DYN_FUNC_ATTR
    #define KSIMD_DYN_FUNC_ATTR KSIMD_SCALAR_INTRINSIC_ATTR

    #if (KSIMD_INSTRUCTION_FEATURE_SCALAR != KSIMD_INSTRUCTION_FEATURE_FALLBACK_VALUE)
        #include KSIMD_DISPATCH_THIS_FILE // dispatch if not fallback
    #endif
#endif


// last dispatch
// once
#undef KSIMD_ONCE
#define KSIMD_ONCE 1

#undef KSIMD_DISPATCH_THIS_FILE
