#pragma once

#include "platform.hpp"

// see https://gcc.gnu.org/onlinedocs/gcc/x86-Function-Attributes.html#x86-Function-Attributes for more intrinsics attributes information

// scalar
#define KSIMD_SCALAR_INTRINSIC_ATTR
#define KSIMD_OP_SCALAR_API \
    KSIMD_FORCE_INLINE \
    KSIMD_FLATTEN \
    KSIMD_SCALAR_INTRINSIC_ATTR


// sse2
#define KSIMD_SSE2_INTRINSIC_ATTR KSIMD_FUNC_ATTR_INTRINSIC_TARGETS("sse2")
#define KSIMD_OP_SSE2_API \
    KSIMD_FORCE_INLINE \
    KSIMD_FLATTEN \
    KSIMD_SSE2_INTRINSIC_ATTR

// sse4.1
#define KSIMD_SSE4_1_INTRINSIC_ATTR KSIMD_FUNC_ATTR_INTRINSIC_TARGETS("sse4.1")
#define KSIMD_OP_SSE4_1_API \
    KSIMD_FORCE_INLINE \
    KSIMD_FLATTEN \
    KSIMD_SSE4_1_INTRINSIC_ATTR


// sse4.2
#define KSIMD_SSE4_2_INTRINSIC_ATTR KSIMD_FUNC_ATTR_INTRINSIC_TARGETS("sse4.2")
#define KSIMD_OP_SSE4_2_API \
    KSIMD_FORCE_INLINE \
    KSIMD_FLATTEN \
    KSIMD_SSE4_2_INTRINSIC_ATTR

// avx2+fma3
#define KSIMD_AVX2_FMA3_INTRINSIC_ATTR KSIMD_FUNC_ATTR_INTRINSIC_TARGETS("avx2,fma")
#define KSIMD_OP_AVX2_FMA3_API \
    KSIMD_FORCE_INLINE \
    KSIMD_FLATTEN \
    KSIMD_AVX2_FMA3_INTRINSIC_ATTR
