name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, arm]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        # with:
        #   submodules: recursive

      - name: Setup QEMU (arm)
        if: matrix.arch == 'arm'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch == 'arm' && 'arm64' || 'x86_64' }}

      - name: Setup SDE (x86)
        if: matrix.arch == 'x86'
        run: |
          wget https://downloadmirror.intel.com/873619/sde-external-10.5.0-2026-01-13-lin.tar.xz
          tar -xf sde-external-10.5.0-2026-01-13-lin.tar.xz
          echo "$(pwd)/sde-external-10.5.0-2026-01-13-lin" >> $GITHUB_PATH

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-17 lld-17 ninja-build
          if [ "${{ matrix.arch }}" = "arm" ]; then
            sudo apt-get install -y g++-aarch64-linux-gnu
          fi

      - name: Run Tests
        run: |
          if [ "${{ matrix.arch }}" = "x86" ]; then
            python3 scripts/test_x86.py --test_mode=max
          else
            python3 scripts/test_arm.py --test_mode=max --sve_bits=128
            python3 scripts/test_arm.py --test_mode=max --sve_bits=256
          fi

      - name: Generate & Test GNU Asm Files
        run: |
          python3 scripts/generate_all_gnu_asm.py
          python3 scripts/test_all_gnu_asm.py