name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, arm]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch == 'arm' && 'arm64' || 'x86_64' }}

      # - name: Install Compilers
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y clang-17 lld-17 ninja-build
      #     if [ "${{ matrix.arch }}" = "arm" ]; then
      #       sudo apt-get install -y g++-aarch64-linux-gnu
      #     fi

      - name: Run Tests
        run: |
          if [ "${{ matrix.arch }}" = "x86" ]; then
            python scripts/test_scalar_x86.py --test_mode=max
          else
            python scripts/test_neon.py --test_mode=max
          fi

      - name: Generate & Test GNU Asm Files
        run: |
          python scripts/generate_all_gnu_asm.py
          python scripts/test_all_gnu_asm.py